name: Loading
favicon: null
layout_spectrum: 1
typography_spectrum: 0.20927
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#26ade4'
    - '#abca49'
    - '#ec0d8e'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.26858418923802674
  rhythmicContrast: 0.75
purpose: []
